name: Schedule Task Generator
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  execute-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python script
        env:
          SUPER_KEY: ${{ secrets.SUPER_KEY }}
        run: python generator.py